apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: sealed-secrets
  repo: https://charts.bitnami.com/bitnami
  version: 1.2.11
  releaseName: sealed-secrets
  namespace: sealed-secrets

resources:
- namespace.yaml